[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "cd backend && npm ci --only=production"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd backend && node server.js"
